### ISSUE TITLE
benefit of calling useTracker

### ISSUE THREAD

**Issue by mvolkmann** [rdb/svelte-meteor-data#6]
What is the difference between lines 3 and 4 below? Both seem to give me a Svelte store that updates whenever the task collection changes.

```js
const query = {};
const projection = { sort: { createdAt: -1 } };
$: tasks1 = useTracker(() => Tasks.find(query, projection).fetch());
$: tasks2 = Tasks.find(query, projection);
```

**Comment by rdb** [comment]
In this specific situation, there is no difference, since cursors behave as reactive stores, and you are encouraged to use the latter form.

The main difference is that the first form will rerun the query when a Meteor dependency changes as well (and not just when a Svelte dependency changes), which becomes important if your query depends on Meteor-reactive calls.  Observe:
```js
$: tasks1 = useTracker(() => Tasks.find({userId: Meteor.userId()}).fetch());
$: tasks2 = Tasks.find({userId: Meteor.userId()});
```
The former will update when the value of `Meteor.userId()` changes, whereas the latter will not, because it doesn't run it inside a useTracker.

That said, you could also fix this by wrapping `Meteor.userId()` inside a Svelte store so that it becomes Svelte-reactive, which is probably better:
```js
$: userIdStore = useTracker(() => Meteor.userId()});
$: tasks3 = Tasks.find({userId: $userIdStore});
```

Finally, if you use `findOne()`, you *have* to use `useTracker()` because it returns a plain object and not a cursor.

**Comment by mvolkmann** [comment]
Thanks for the thorough explanation!
